name: 'cloud'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  cloud189:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade DecryptLogin
    - name: 'cloud189'
      env:
        NETEASE_USERNAME: ${{ secrets.NETEASE_USERNAME }}
        NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
      run: DecryptLogin/core/cloud189.py
